id: PRD_0BMW1N
name: Benutzerkonto mit Mailbox
version: 0.1.0
description: Reference product for Nomos MVP
requirement_ids:
    - REQ_T76CAZ
    - REQ_BXSE37
rule_ids:
    - RUL_P4WM0C
    - RUL_BENGD4
