/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#fcf8ff',
        'surface-dim': '#dcd8e5',
        'surface-bright': '#fcf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f2ff',
        'surface-container': '#f0ecf9',
        'surface-container-high': '#eae6f4',
        'surface-container-highest': '#e4e1ee',
        'on-surface': '#1b1b24',
        'on-surface-variant': '#464555',
        'inverse-surface': '#302f39',
        'inverse-on-surface': '#f3effc',
        outline: '#777587',
        'outline-variant': '#c7c4d8',
        'surface-tint': '#4d44e3',
        primary: '#3525cd',
        'on-primary': '#ffffff',
        'primary-container': '#4f46e5',
        'on-primary-container': '#dad7ff',
        'inverse-primary': '#c3c0ff',
        secondary: '#515f74',
        'on-secondary': '#ffffff',
        'secondary-container': '#d5e3fc',
        'on-secondary-container': '#57657a',
        tertiary: '#7e3000',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#a44100',
        'on-tertiary-container': '#ffd2be',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#e2dfff',
        'primary-fixed-dim': '#c3c0ff',
        'on-primary-fixed': '#0f0069',
        'on-primary-fixed-variant': '#3323cc',
        'secondary-fixed': '#d5e3fc',
        'secondary-fixed-dim': '#b9c7df',
        'on-secondary-fixed': '#0d1c2e',
        'on-secondary-fixed-variant': '#3a485b',
        'tertiary-fixed': '#ffdbcc',
        'tertiary-fixed-dim': '#ffb695',
        'on-tertiary-fixed': '#351000',
        'on-tertiary-fixed-variant': '#7b2f00',
        background: '#fcf8ff',
        'on-background': '#1b1b24',
        'surface-variant': '#e4e1ee',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['monospace'],
      },
      borderRadius: {
        'xl': '1.5rem',
        '2xl': '1rem',
        'lg': '0.75rem',
        'md': '0.5rem',
      },
      boxShadow: {
        'card': '0 1px 3px rgba(71, 85, 105, 0.07), 0 1px 2px rgba(71, 85, 105, 0.04)',
        'card-hover': '0 4px 6px rgba(71, 85, 105, 0.08), 0 2px 4px rgba(71, 85, 105, 0.04)',
        'panel': '0 10px 15px -3px rgba(71, 85, 105, 0.1), 0 4px 6px -2px rgba(71, 85, 105, 0.05)',
      },
    },
  },
  plugins: [],
}
