---
- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart nomos
  systemd:
    name: nomos
    state: restarted

- name: restart nomos-mcp
  systemd:
    name: nomos-mcp
    state: restarted

- name: restart nomos docker
  command: docker restart nomos
